name: "QHub validate linter"

on:
  pull_request:
    branches:
      - "{{ cookiecutter.ci_cd.branch }}"
    paths:
      - "qhub-config.yaml"


jobs:
  qhub-validate:
    name: 'Qhub'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Infastructure'
        uses: actions/checkout@master
        with:
          token: {{ '${{ secrets.REPOSITORY_ACCESS_TOKEN }}' }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install qhub
        run: |
          {{ cookiecutter.pip_install_qhub }}
      - name: 'Qhub Linterfy'
        env:
          PR_NUMBER: {{ '${{ github.event.number }}' }}
          REPO_NAME : {{ '${{ github.repository }}' }}
          GITHUB_TOKEN: {{ '${{ secrets.REPOSITORY_ACCESS_TOKEN }}' }}
        run: |
          qhub validate qhub-config.yaml --enable-commenting