blank_issues_enabled: false
contact_links:
  - name: Anymlops Documentation
    url: https://www.nebari.dev/docs/
    about: Check out the Anymlops documentation
  - name: Anymlops Discussions - our user forum
    url: https://github.com/orgs/nebari-dev/discussions
    about: Ask questions, discuss RFDs and help other Anymlops's users
  - name: Documentation issues 📖
    about: Did you find an error in our documentation? Report your findings here.
    url: https://github.com/nebari-dev/nebari-docs/issues/new/choose
  - name: (maintainers only) - Blank issue
    url: https://github.com/nebari-dev/nebari/issues/new
    about: For maintainers only - should be used sparingly
