on: 
  push:
    branches: 
    - main
jobs:
  run:
    runs-on: ubuntu-18.04
    steps:
    - uses: docker://pandoc/latex:2.9
    - uses: actions/checkout@main
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7' # Version range or exact version of Python to use, using semvers version range syntax.
        architecture: 'x64' # (x64 or x86)
    - run: |
        sudo apt install pandoc
        pip install sphinx
        pip install -rdocs/requirements.txt
        sphinx-build docs build
        echo qhub.dev > build/CNAME
        touch build/.nojekyll
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: main # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build
