name: "Close stale issues"
on:
  schedule:
  # runs at 00:15 on every Monday
  - cron: "15 00 * * MON"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been automatically marked as stale because there was no recent activity in 60 days. Remove the stale label or add a comment, otherwise, this issue will automatically be closed in 7 days if no further activity occurs.'
        close-issue-message: 'This issue was closed because it has been stalled for 7 days with no activity.'
        days-before-stale: 60
        days-before-close: 7
