name: "Tests"

on:
  push:
    branches:
      - master

jobs:
  test-general:
    name: 'Test Package'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - name: 'Checkout Infastructure'
        uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install QHub
        run: |
          pip install .[dev]
      - name: Black Formatting
        run: |
          black --check qhub
      - name: Flake8 Formatting
        run: |
          flake8
      - name: Test QHub
        run: |
          pytest

  test-digital-ocean:
    name: 'Test Digital Ocean Deployment'
    runs-on: ubuntu-latest
    needs: test-general
    steps:
      - name: 'Checkout Infastructure'
        uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install QHub
        run: |
          pip install .[dev]
      - name: QHub Build Digital Ocean template
        run: |
          qhub render -c tests/assets/config_do.yaml -o qhub-do-deployment
      - name: Digital Ocean Artifact
        uses: actions/upload-artifact@v1
        with:
          name: qhub-digital-ocean-artifact
          path: qhub-do-deployment

  test-amazon-web-services:
    name: 'Test Amazon Web Services Deployment'
    runs-on: ubuntu-latest
    needs: test-general
    steps:
      - name: 'Checkout Infastructure'
        uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install QHub
        run: |
          pip install .[dev]
      - name: QHub Build Amazon Web Services Template
        run: |
          qhub render -c tests/assets/config_aws.yaml -o qhub-aws-deployment
      - name: Amazon Web Services Artifact
        uses: actions/upload-artifact@v1
        with:
          name: qhub-amazon-web-services-artifact
          path: qhub-aws-deployment


  test-google-cloud-platform:
    name: 'Test Google Cloud Platform Deployment'
    runs-on: ubuntu-latest
    needs: test-general
    steps:
      - name: 'Checkout Infastructure'
        uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install QHub
        run: |
          pip install .[dev]
      - name: QHub Build Google Cloud Platform Template
        run: |
          qhub render -c tests/assets/config_gcp.yaml -o qhub-gcp-deployment
      - name: Google Cloud Platform Artifact
        uses: actions/upload-artifact@v1
        with:
          name: qhub-google-cloud-platform-artifact
          path: qhub-gcp-deployment
