name: "Test PR"

on:
  pull_request:
    branches:
      - master


jobs:
  test-general:
    name: 'Test Package'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
      - name: 'Checkout Infastructure'
        uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install QHub
        run: |
          pip install .[dev]
      - name: Black Formatting
        run: |
          black --check qhub
      - name: Flake8 Formatting
        run: |
          flake8
      - name: Test QHub
        run: |
          pytest
